### ISSUE TITLE
Health Stories Project Idea 

### ISSUE THREAD

**Issue by idantb101** [FACN3/facn3-projects#5]
WHAT?

my idea is to create a website that will contain diseases stories.
the site will allow users to tell a story of a person fighting a disease in great details
by a specific structure and free space.  
and allow all people to read those stories and tips for good information to learn from. 

WHY ?  *-*

do something good !
i thought a lot about what should i do as a project and asking around for a good idea.
i decided going this direction because i really think this app could be use full for a lot of people 
and i was looking for a project i would be passion about, even after those three weeks. 

THE PESRONAL PICTURE 

accompany  a person  fighting a disease is much more then scary or frightening
or any other word. it is just un describable.
and when you look online the are so much data that most of it is useless.
in my case we learned a lot the hard way.
we lost. 
know if we would go again there is so much staff we would do differently.
when you loose the hardest thing for you is admit your mistakes because it is not a game but life.
if we could only give those useful tips to those who fight the same thing a round the globe. just 
maybe they could win. 

HOW 

the app would be build in vue.js in the front.
for the db i suggest postgres(flexible).
with a css library, it should be lite and to the point ? feel welcome to suggest. (not bootstrap).
in nodejs express(flexible).

STRUCTURE (BASIC AND FLEXIBLE)

sign up page
 log in page
recover password page
add story page 
main page containing all stories
smart search page

The Most Important Part
Why Should You Join This Team : 

we here to learn together in a fun environment.
we are committed and plan to work hard and learn new staff.
we are here to work together as a team, and we will leave no man behind.
no slacking ! ! !
having fun   :1st_place_medal: 

sorry for the bad English, please fix any spelling mistake you find.
if you have question feel free to ask me here or privatlly.
^-^

**Comment by NickP123** [comment]
I’d like to join you with this one Idan. Sounds amazing.

**Comment by shiryz** [comment]
Closing for no longer relevant
