### ISSUE TITLE
Online cards game

### ISSUE THREAD

**Issue by hasansaad1** [FACN3/facn3-projects#6]
The first project -
What?
An online card game (west) which offers the players to play against each other and watch other ongoing games 
Why?
The site will offer a good experience for an online card game , which will also give us as developers to implement various of technologies and mold the experience into something that gamers would want to keep playing. 
How?
The game will offer the user two experiences to play and to watch a game , a game will include 4 players ,  each game consists of number of rounds and the team that wins is the team that wins certain amount of points which will be collected in the 13 turns of each round. 
Upon that the player gains points for his profile on each game he plays.

**Comment by SamiSha99** [comment]
That's a great idea, can I get a set of rules over west? I kinda forgot how the game works..

**Comment by hasansaad1** [comment]
Yeah sure , and we’ll also add instructions in the website :+1:

**Comment by shiryz** [comment]
Closing for no longer relevant
