### ISSUE TITLE
customized/bespoke news aggregator

### ISSUE THREAD

**Issue by sophiavocado** [FACN3/facn3-projects#7]
### WHAT
It is a customized news aggregator.
A user will get notification as well as a track of 

### HOW
1. Users authenticate using third party application. (ex. fb, github..)  "O AUTH api"
2. Users choose topics they are interested in
3. Using news APIs, application continuously go through news websites to find related articles.
4. Once an article or more matched the user preferences found, a notification will be sent to the user.
5. When the user goes to "personalized  page", the user can check the track of his matched articles, as well as a description of each article that includes "phrase frequency" using D3JS library. 

### WHY 
Instead of going through all the media websites to check out about a topic or a category of news that you usually follow, you will get a notification and a saved track of the related articles, "all in one place

### TECHNOLOGY USED: 
Oauth API 
D3js, Python NTLK

**Comment by shiryz** [comment]
Closing for no longer relevant

**Comment by shiryz** [comment]
Demo purposes :ghost:
